# Generated by Django 6.0.2 on 2026-02-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'Menu Categories'},
        ),
        migrations.AlterModelOptions(
            name='restaurantinfo',
            options={'verbose_name_plural': 'Restaurant Information'},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
